version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=ctf_password
      - DB_NAME=user_management
    volumes:
      - .:/var/www/html
    networks:
      - ctf_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ctf_password
      MYSQL_DATABASE: user_management
    ports:
      - "3306:3306"
    volumes:
      - ./initData.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - ctf_network

volumes:
  mysql_data:

networks:
  ctf_network:
    driver: bridge
